### ISSUE TITLE
How can I create the address if I want to share it later? (probably not a showstopper)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#240]
Currently when I press "Receive" the address will be created only if I share it somehow right now. If I wanna use that address later I need to tap "Share" and then tap "Copy" or actually share it somewhere. Maybe there should be an easier way to create an address without sharing.

**Comment by alexandrashelenkova** [comment]
Updates screes here:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5cee7c2d4c7fea1d62dc3144

If user only opened screen and didn't do anything at all and used back button address shouldn't be created.
If user made some changes on the screen and used back button show that alert https://zpl.io/beKWRlB
Tap on "Close and save address for later" button should bring user back to the previous screen (address created and saved).

**Comment by Denis-Asipenko** [comment]
When you tap "change" no alert should be given.
![image](https://user-images.githubusercontent.com/45556620/60891135-5dc37d00-a265-11e9-8209-e2e4f88b128d.png)
If the user wants to select an existing address instead of the generated one, it is necessary to display all active addresses with auto-generated at the beginning of the list.
Example:
![image](https://user-images.githubusercontent.com/45556620/60891570-391bd500-a266-11e9-9312-2f9b9b429334.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/61207567-18d49600-a6fe-11e9-98c6-b69afcc81b8b.png)

**Comment by Denis-Asipenko** [comment]
checked
