### ISSUE TITLE
Sidemenu redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#302]
Update sidemenu to new colours (+ add logo)
New version is here https://zpl.io/bAE0JWx

**Comment by alexandrashelenkova** [comment]
<img width="479" alt="Screenshot 2019-08-21 at 18 23 11" src="https://user-images.githubusercontent.com/7249484/63424325-c1ce8900-c440-11e9-95ab-be3060ec62fb.png">

**Comment by Denis-Asipenko** [comment]
Design:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5bbb21eb252aba5fcdfaed6d
![image](https://user-images.githubusercontent.com/45556620/63694753-d1264b80-c81f-11e9-940e-633ba73d2535.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/63694788-e1d6c180-c81f-11e9-8d6d-bba9e33d856f.png)
This bug will be fixed in the next sprint. Agreed with @alexandrashelenkova
