### ISSUE TITLE
Show estimated height for maturing UTXO

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#385]

**Comment by dariatarakanova** [comment]
- Show estimated height for maturing UTXO - https://zpl.io/anLXjKQ
- Add "since date" for available and unavailable UTXO - https://zpl.io/VOArlWP and https://zpl.io/2jYOAwp
- Add estimated height and since date on detail UTXO screen as well - https://zpl.io/2pkmZAy

**Comment by Denis-Asipenko** [comment]
checked

**Comment by Denis-Asipenko** [comment]
Please add for other tabs.
Example:
![image](https://user-images.githubusercontent.com/45556620/72340989-3e0c8600-36da-11ea-8e27-9808b31d08db.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/72340687-ac047d80-36d9-11ea-899e-7b4f4a802b3a.png)

**Comment by Denis-Asipenko** [comment]
Please change with "Available (since ****** block height  )" on "**Available (since  block height ****** )**"
Design:
![image](https://user-images.githubusercontent.com/45556620/72422007-a3bc4900-3792-11ea-84f4-5395a71b33ff.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/72422228-19c0b000-3793-11ea-9a4c-7f3107d86744.png)

**Comment by Denis-Asipenko** [comment]
checked
