### ISSUE TITLE
Rework search results design on transaction's screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#612]
1) Highlight with blue color #611 
2) Update design of search results: add separator, make titles in caps (as on transaction details screen) https://zpl.io/bJGNzO3
![image](https://user-images.githubusercontent.com/47353570/136454247-ad7c1311-2c6b-428e-ab6a-153d41ac92b0.png)

3) Search by name https://zpl.io/aMxxY13
![image](https://user-images.githubusercontent.com/47353570/136454281-b75a2139-a298-4c30-ba33-7602da7a0bc3.png)

4) If no search results display text "There are no transactions matching search criteria", instead of "Your transaction list is empty" https://zpl.io/aRKKQ9E
![image](https://user-images.githubusercontent.com/47353570/136454335-dc1aa360-c293-4fa6-9484-375d09492dfe.png)

5) Adjust top bar to new design (see current implementation below).  Make it a lighter and solid color from the very top. 
![image](https://user-images.githubusercontent.com/47353570/136454400-56f6e8e1-6b9f-4ba2-a1cc-5b9959e4170c.png)

![image](https://user-images.githubusercontent.com/47353570/136454643-b59cab74-2311-4bad-a676-a8384b1121c4.png)

Current implementation:
![telegram-cloud-photo-size-2-5404695302809696167-y](https://user-images.githubusercontent.com/47353570/136454173-1893d272-e34c-409e-8aea-4fb847c2a15f.jpg)

**Comment by KatsiarynaV** [comment]
1. When searching by the sending address the receiving address is displayed instead of the sending one
![06](https://user-images.githubusercontent.com/68267190/158531393-a38792f8-42df-4450-bd98-997faed37608.jpg)

2. Please add an indent between the fields. For the field's name make the letter spacing as in the design
![10](https://user-images.githubusercontent.com/68267190/158531629-97ea7611-388d-45a8-b96a-c89e083ad383.jpg)

3. Place "comment" field under the receiving (sending) address 
![15](https://user-images.githubusercontent.com/68267190/158532179-c9bba696-4b0b-41b2-890b-8efbf715bc1b.jpg)

**Comment by KatsiarynaV** [comment]
1. When searching by the sending address this address isn't displayed - **for sent transactions**
![25](https://user-images.githubusercontent.com/68267190/158948076-09e5eb61-cebe-4955-a126-19ff2780883b.jpg)
![26](https://user-images.githubusercontent.com/68267190/158948078-79d5b134-feed-4bbc-8a09-2f53b2a4339c.jpg)

2. For fields names make font (the letter spacing) as in the design
![28](https://user-images.githubusercontent.com/68267190/158948530-d5b775dc-47c7-446b-a863-c1328b095d09.jpg)

3. If we search by comment and the Kernel ID has the same first letter as the comment then the search result with this Kernel isn't disappeared when entering next letters
![29](https://user-images.githubusercontent.com/68267190/158949213-7d13cb5e-25bf-496c-bec9-f30ff9b7b4b5.jpg)

**Comment by KatsiarynaV** [comment]
Checked
